#!/usr/bin/env bash
# local-ai-stack — univerzální installer
#
# AUTO-DETECTE: GPU architekturu, IP adresu stroje, NFS mount, modely
# GENERUJE: .env (pokud chybí) + machines.yaml + .gitignore úpravy
# DELEGATE: per-machine setup skriptu ze submoduleu
# BUILD: Docker images (submodul build context)
# UP: docker compose s profilem
#
# Použití:
#   ./scripts/install.sh                  # default (plná instalace)
#   ./scripts/install.sh --no-build      # přeskočí docker build (pro testy)
#   ./scripts/install.sh --no-up         # nestartuje kontejnery
#   ./scripts/install.sh --force         # přegeneruj .env a machines.yaml
set -euo pipefail
cd "$(dirname "$0")/.."

# ── Argumenty ───────────────────────────────────────────
NO_BUILD=0
NO_UP=0
FORCE=0
for arg in "$@"; do
  case "$arg" in
    --no-build) NO_BUILD=1 ;;
    --no-up)    NO_UP=1 ;;
    --force)    FORCE=1 ;;
    -h|--help)
      grep '^# ' "$0" | sed 's/^# //; s/^#//'
      exit 0
      ;;
    *) echo "ERROR: neznámý argument '$arg'" >&2; exit 1 ;;
  esac
done

echo "=== local-ai-stack install ==="

# ── 1) Git submoduly ─────────────────────────────────────
if [ ! -f .gitmodules ]; then
  echo "ERROR: musíš být v local-ai-stack rootu (.gitmodules chybí)" >&2
  exit 1
fi
git submodule update --init --recursive

# ── 2) Auto-detekce GPU ─────────────────────────────────
command -v nvidia-smi &>/dev/null || { echo "ERROR: nvidia-smi chybí" >&2; exit 1; }
GPU_NAME="$(nvidia-smi --query-gpu=name --format=csv,noheader | head -1)"
echo "  GPU: $GPU_NAME"

case "$GPU_NAME" in
  *P40*)
    MACHINE_ID=aicore;   GPU_ARCH=61;   GGML_CUDA_ARCH=61
    CUDA_BASE=nvidia/cuda:12.4.1-runtime-ubuntu22.04
    TORCH_INDEX=cu124
    COMFYUI_EXTRA_ARGS="--use-pytorch-cross-attention --highvram"
    MOSS_MULTI_GPU=0
    ;;
  *5060*)
    MACHINE_ID=aiworker; GPU_ARCH=120;  GGML_CUDA_ARCH=120
    CUDA_BASE=nvidia/cuda:13.0.3-runtime-ubuntu24.04
    TORCH_INDEX=cu130
    COMFYUI_EXTRA_ARGS="--use-pytorch-cross-attention --fast --bf16-unet"
    MOSS_MULTI_GPU=1
    ;;
  *3070*)
    MACHINE_ID=desktop;  GPU_ARCH=86;   GGML_CUDA_ARCH=86
    CUDA_BASE=nvidia/cuda:12.4.1-runtime-ubuntu22.04
    TORCH_INDEX=cu124
    COMFYUI_EXTRA_ARGS="--use-pytorch-cross-attention --fast"
    MOSS_MULTI_GPU=0
    ;;
  *6800*)
    MACHINE_ID=desktop;  GPU_ARCH=1030; GGML_CUDA_ARCH=1030
    CUDA_BASE=rocm/dev-ubuntu-22.04:6.2.4
    TORCH_INDEX=rocm6.2
    COMFYUI_EXTRA_ARGS="--use-pytorch-cross-attention --fast"
    MOSS_MULTI_GPU=0
    ;;
  *) echo "ERROR: neznámá GPU: $GPU_NAME" >&2; exit 1 ;;
esac
echo "  Detekoval jsem: $MACHINE_ID (sm_$GPU_ARCH)"

# ── 2b) Výběr LLM modelu z registru (žádné hardcoded modely!) ──
# Modely jsou VŽDY na NFS (/mnt/models), nikdy lokálně. Registry
# (llm_registry.json) je jediný zdroj pravdy — analogie k
# comfyui-unified/model_registry.json pro IMG.
if [ -n "${QWEN_MODEL_ID:-}" ]; then
  echo "  Operátor zvolil QWEN_MODEL_ID=$QWEN_MODEL_ID"
fi
LLM_SELECT="$(./scripts/llm-select.sh)" || { echo "ERROR: výběr LLM modelu selhal" >&2; exit 1; }
eval "$LLM_SELECT"
echo "  LLM model: $QWEN_MODEL_ID ($QWEN_MODEL, ctx=$CTX_SIZE, cache_k=$CACHE_TYPE_K)"

# ── 3) Auto-detekce IP adresy stroje ─────────────────────
# Zkusíme různé zdroje (první úspěšný vyhraje)
detect_ip() {
  # 1) hostname -I (primární IP bez DNS resolving)
  local ip
  ip="$(hostname -I 2>/dev/null | awk '{print $1}')"
  [ -n "$ip" ] && [ "$ip" != "127.0.0.1" ] && echo "$ip" && return 0

  # 2) ip route (default route interface IP)
  ip="$(ip route get 1.1.1.1 2>/dev/null | awk '/src/ {print $7; exit}')"
  [ -n "$ip" ] && [ "$ip" != "127.0.0.1" ] && echo "$ip" && return 0

  # 3) ip addr (první non-loopback IPv4)
  ip="$(ip -4 addr show scope global 2>/dev/null | awk '/inet / {print $2}' | head -1 | cut -d/ -f1)"
  [ -n "$ip" ] && [ "$ip" != "127.0.0.1" ] && echo "$ip" && return 0

  return 1
}

MY_IP="$(detect_ip || true)"
if [ -z "$MY_IP" ]; then
  echo "  WARN: Nepodařilo se automaticky detekovat IP. Ptej se:"
  read -p "  Zadej IP adresu tohoto stroje (LAN): " MY_IP
fi
echo "  IP adresa: $MY_IP"

# ── 4) Generuj .env (pokud chybí, --force, nebo MACHINE_ID nesedí) ──
ENV_NEEDS_REGENERATION=0
if [ -f .env ]; then
  # Pokud .env má jiný MACHINE_ID než detekovaný → přegeneruj (stroj se změnil)
  ENV_MACHINE_ID="$(grep -E '^MACHINE_ID=' .env | head -1 | cut -d= -f2)"
  if [ -n "$ENV_MACHINE_ID" ] && [ "$ENV_MACHINE_ID" != "$MACHINE_ID" ]; then
    echo "  WARN: .env má MACHINE_ID=$ENV_MACHINE_ID, ale detekován $MACHINE_ID — přegeneruji"
    ENV_NEEDS_REGENERATION=1
  fi
fi

if [ ! -f .env ] || [ "$FORCE" -eq 1 ] || [ "$ENV_NEEDS_REGENERATION" -eq 1 ]; then
  echo "  Generuji .env (per-machine)..."
  cat > .env <<EOF
# local-ai-stack — auto-generated by install.sh ($(date -Iseconds))
# Edituj ručně pro overrides, jinak install.sh s --force přegeneruje

# Stroj identifikace
MACHINE_ID=$MACHINE_ID

# GPU architektura
GPU_ARCH=$GPU_ARCH
GGML_CUDA_ARCH=$GGML_CUDA_ARCH
CUDA_DEVICE=auto
GPU_DEVICE_ID=0
# ComfyUI GPU: aiworker má 2× GPU — qwen drží GPU 0, comfyui jde na GPU 1.
# aicore/desktop mají 1× GPU — comfyui jde na GPU 0 (sdílené, on-demand).
COMFYUI_GPU_ID=$([ "$MACHINE_ID" = "aiworker" ] && echo 1 || echo 0)
MOSS_MULTI_GPU=$MOSS_MULTI_GPU

# ComfyUI build args
CUDA_BASE=$CUDA_BASE
TORCH_VERSION=2.5.1
TORCH_VISION=0.20.1
TORCH_AUDIO=2.5.1
TORCH_INDEX=$TORCH_INDEX
COMFYUI_EXTRA_ARGS=$COMFYUI_EXTRA_ARGS

# Modely (NFS mount — VŽDY NFS, nikdy lokálně)
MODEL_DIR=/mnt/models
QWEN_MODEL=$QWEN_MODEL
QWEN_MODEL_ID=$QWEN_MODEL_ID
QWEN_PORT=8085
CTX_SIZE=$CTX_SIZE
CACHE_TYPE_K=$CACHE_TYPE_K
CACHE_TYPE_V=$CACHE_TYPE_V
SPEC_TYPE=$SPEC_TYPE
SPEC_DRAFT_N_MAX=$SPEC_DRAFT_N_MAX

# Hub-UI
HUB_PROBE_INTERVAL=5
HUB_GENERATE_TIMEOUT=600
CLUSTER_MODE=manual

# Stroje v clusteru (auto-detekované pro tento stroj, ostatní defaulty)
${MACHINE_ID^^}_HOST=$MY_IP
AICORE_HOST=\${AICORE_HOST:-192.168.10.60}
DESKTOP_HOST=\${DESKTOP_HOST:-192.168.10.228}
EOF
  echo "  .env vytvořen. MACHINE_ID=$MACHINE_ID, IP=$MY_IP"
else
  echo "  .env existuje (--force pro regeneraci), nechávám"
fi

# ── 5) Generuj machines.yaml z .env IPs ─────────────────
if [ ! -f hub-ui/machines.yaml ] || [ "$FORCE" -eq 1 ]; then
  echo "  Generuji hub-ui/machines.yaml z .env IPs..."
  # Načti IPs z .env (fallback na defaulty pokud chybí)
  source .env 2>/dev/null || true
  AICORE_HOST="${AICORE_HOST:-192.168.10.60}"
  AIWORKER_HOST="${AIWORKER_HOST:-192.168.10.194}"
  DESKTOP_HOST="${DESKTOP_HOST:-192.168.10.228}"

  sed -e "s|\${AICORE_HOST}|$AICORE_HOST|g" \
      -e "s|\${AIWORKER_HOST}|$AIWORKER_HOST|g" \
      -e "s|\${DESKTOP_HOST}|$DESKTOP_HOST|g" \
      hub-ui/machines.example.yaml > hub-ui/machines.yaml
  echo "    aicore=$AICORE_HOST, aiworker=$AIWORKER_HOST, desktop=$DESKTOP_HOST"
  echo "    Smaž machines.yaml + spusť install.sh znovu pro jiné IP adresy."
else
  echo "  machines.yaml existuje, nechávám (--force pro regeneraci)"
fi

# ── 6) NFS check + LLM model download ──────────────────
MODEL_DIR="${MODEL_DIR:-/mnt/models}"
if [ ! -d "$MODEL_DIR" ]; then
  echo "  WARN: $MODEL_DIR neexistuje, modely se nestáhnou"
fi

# ── 7) Model check (download jen pokud chybí) ────────────
# POZNÁMKA: docker compose build + up dělá master sám (krok 8+9).
# Submodule setup-*.sh dělá docker compose take — proto ho nevoláme.
# Pro standalone setup bez local-ai-stack můžeš jet setup-aicore.sh
# přímo ze submoduleu.
#
# POZOR: download-models.sh default je /mnt/models/llama. My chceme stahovat
# do /mnt/models (root, kde jsou modely už uloženy). Proto nepřidáváme /llama.
if [ -d "$MODEL_DIR" ]; then
  echo "  Stahuji LLM modely do $MODEL_DIR (pokud chybí)..."
  (cd local-ai-coding-servers && MODEL_DIR="$MODEL_DIR" ./scripts/download-models.sh) || \
    echo "  WARN: download selhal (offline? skip)"
else
  echo "  SKIP: $MODEL_DIR neexistuje"
fi

# ── 8) Docker compose build ────────────────────────────
if [ "$NO_BUILD" -eq 0 ]; then
  echo "  Docker compose build (může trvat 10-30 min poprvé)..."
  docker compose --profile "$MACHINE_ID" build 2>&1 | tail -20
else
  echo "  --no-build, skip Docker build"
fi

# ── 9) Docker compose up ────────────────────────────────
if [ "$NO_UP" -eq 0 ]; then
  echo "  Docker compose up -d (profil: $MACHINE_ID, force-recreate)..."
  # force-recreate: kontejnery musí vždy nabrat nový kód (server.py je
  # mountnutý z masteru, ale bez recreate kontejner běží se starou verzí)
  docker compose --profile "$MACHINE_ID" up -d --force-recreate
else
  echo "  --no-up, skip Docker compose up"
fi

# ── 10) Hotovo ──────────────────────────────────────────
echo ""
echo "=== Hotovo ==="
echo "  Stroj: $MACHINE_ID ($GPU_NAME) @ $MY_IP"
echo "  Hub-UI:    http://localhost:8288"
echo "  ComfyUI:   http://localhost:8188 (API), http://localhost:8189 (WebUI)"
echo "  Qwen:      http://localhost:8085"
echo "  Agent:     http://localhost:8199/capabilities"
echo "  WebUI discovery: http://localhost:8288/api/webui/registry"
echo ""
echo "Pokud chceš přegenerovat .env a machines.yaml (jiné IP):"
echo "  ./scripts/install.sh --force --no-build --no-up"
